### PR TITLE
Fixed all race conditions in tests in multiple packages

### LINKED ISSUE #5289: Race conditions causing flaky unit test for pubsub unsubscribe on Windows
## In what area(s)?

 /area runtime

> /area operator

> /area placement

> /area docs

> /area test-and-release

## What version of Dapr?

1.9

## Expected Behavior

This unit test seems to fail with some frequency on Windows:

image

## Actual Behavior

Unit test runs at 100% success rate (5 times in a row should be enough).

## Steps to Reproduce the Problem

Run the unit test on Windows.

## Release Note

RELEASE NOTE:

### PR DESCRIPTION
**Pull request by ItalyPaleAle**
Fixes #5289

Fixes race conditions in multiple packages (most notably pkg/runtime and pkg/actors, among others), so running `go test -race .` reports no errors.

### CODE REVIEW

**Comment by artursouza** [comment]
> Fixes #5289
> 
> Now, running `go test . -race` in pkg/runtime reports no data races

Can you create a PR adding that to the validation steps for our build going forward? Going into the master branch for that is fine.

**Review by artursouza — DISMISSED** [review]

File: pkg/runtime/runtime.go [hunk 1]
```diff
@@ -1749,6 +1748,9 @@ func (a *DaprRuntime) initPubSub(c componentsV1alpha1.Component) error {
 // And then forward them to the Pub/Sub component.
 // This method is used by the HTTP and gRPC APIs.
 func (a *DaprRuntime) Publish(req *pubsub.PublishRequest) error {
+	a.topicsLock.RLock()
```
Comment (yaron2) [inline pkg/runtime/runtime.go:1751]: This is likely to have adverse performance implications. If races here are rare (for example, occuring only when someone is trying to publish a message while processing subscriptions on init), I'd remove this.

**Review by yaron2 — CHANGES_REQUESTED** [review]

File: pkg/runtime/runtime.go (hunk 1 above)
Comment (ItalyPaleAle) [reply pkg/runtime/runtime.go:1751]: It can happen every time the subscriptions are changed, for example if apphealth is turning pubsub off.

Although this will negatively impact performance a bit due to the overhead of acquiring a lock, I am using a RWMutex with a read-lock here, so it doesn't block if other goroutines are trying to publish at the same time. It will only block if there's an operation that's modifying the topics/subscriptions concurrently.

What do you think?

Comment (artursouza) [reply pkg/runtime/runtime.go:1751]: Is there a way to have this map to be immutable?

Comment (artursouza) [reply pkg/runtime/runtime.go:1751]: I prefer the correctness over the performance here. BTW, we don't have performance tests for pubsub (yet).

Comment (yaron2) [reply pkg/runtime/runtime.go:1751]: At the very least then lock when accessing the map and not the entire function?

Comment (ItalyPaleAle) [reply pkg/runtime/runtime.go:1751]: That sounds very reasonable. Will do

Comment (yaron2) [reply pkg/runtime/runtime.go:1751]: > I prefer the correctness over the performance here. BTW, we don't have performance tests for pubsub (yet).

We actually do have pub/sub perf tests, courtesy of @skyao

**Comment by ItalyPaleAle** [comment]
@yaron2 changed the lock in the runtime

Also: 

1. `go test -race` passes on pkg/actors too now
1. added a `make test-race` with 3 packages that are known to pass. I'll use that for a pipeline in another PR targeting master

**Review by yaron2 — APPROVED** [review]

**Comment by mukundansundar** [comment]
Qq on this PR should we add a CI check only for files that currently do not have race and fail if they are introduced later on?
@dapr/maintainers-dapr @ItalyPaleAle

**Comment by ItalyPaleAle** [comment]
> Qq on this PR should we add a CI check only for files that currently do not have race and fail if they are introduced later on?

Yes, @artursouza requested that already:

> Can you create a PR adding that to the validation steps for our build going forward? Going into the master branch for that is fine.

I will do that on Monday, I was just waiting for this PR to be merged.
