### PR TITLE
Fix ServiceInvocation stream buffering

### LINKED ISSUE #9626: [Service Invoke] HTTP Responses which are streamed via chunked transfer are buffered in sidecar
Probably affects all versions of dapr

---

Full repro instructions here 

https://github.com/olitomlinson/dapr-large-file-streaming/blob/ui/STREAMING_RESPONSE_ISSUE.md

**MAKE SURE TO SWAP TO THE `UI` BRANCH AS `MAIN` IS A DIFFERENT ISSUE**

---

**Actual**

When a request is made which returns a streamed response, the **entire response** is buffered in the sidecar memory.

**Expected**

When a request is made which returns a streamed response, the entire response is NOT buffered in the sidecar memory.

### PR DESCRIPTION
**Pull request by JoshVanL**
Service invocation buffers entire streaming request body in memory

Problem

When sending a request with a streaming body (chunked transfer encoding) through Dapr HTTP service invocation, the sidecar buffered the entire request body in memory before forwarding it. For large payloads—such as file uploads or long-running data streams—this caused excessive memory usage and potential out-of-memory crashes.

Impact

Any HTTP service invocation request without a known `Content-Length` (e.g. chunked uploads, streamed data, piped bodies) had its entire body buffered in memory by the sending sidecar. This made Dapr unsuitable for streaming large payloads between services and could cause sidecar OOM kills in production.

Root Cause

The sidecar's retry mechanism unconditionally buffered the request body into memory so it could replay the body on retry. For streaming requests, the body cannot be replayed because it is consumed as it is read, making the buffering both unnecessary and harmful.

Solution

The sidecar now detects streaming requests (those with no known content length) and skips request body buffering entirely. Both the built-in retry logic and any user-configured resiliency retry policies are automatically bypassed for streaming requests, since retrying would require re-reading a body that has already been consumed. Non-streaming requests with a known `Content-Length` continue to support retries as before.

---

Service invocation buffers entire streaming response body in memory

Problem

When proxying HTTP responses through service invocation, the sidecar buffered the entire response body in memory before forwarding it to the caller.
For large or unbounded streaming responses, this caused excessive memory usage and potential out-of-memory crashes.

Impact

Any service invocation response with a large or streaming body could cause sidecar OOM kills, regardless of HTTP status code.
This made Dapr unsuitable for proxying streaming responses such as server-sent events, file downloads, or long-running data streams between services.

Root Cause

The sidecar's resiliency mechanism read the full response body into memory so it could evaluate whether to retry the request.
When the request itself is a stream that has already been consumed, retries are impossible regardless of the response, making the buffering unnecessary.

Solution

For streaming requests, the sidecar now forwards response bodies directly to the caller without buffering them in memory.
Resiliency features like circuit breakers continue to track failures normally.
Non-streaming requests continue to support retries and buffered error handling as before.

---

Fixes https://github.com/dapr/dapr/issues/9626 https://github.com/dapr/dapr/issues/9625

### CODE REVIEW

File: pkg/api/http/directmessaging.go
Comment (acroca) [inline pkg/api/http/directmessaging.go]: Shouldn't this `defer` be higher so it's closed even when we do early returns?

File: pkg/api/http/directmessaging.go [hunk 1]
```diff
@@ -202,14 +216,24 @@ func (a *api) onDirectMessage(w http.ResponseWriter, r *http.Request) {
...
 		} else if resStatus.GetCode() < 200 || resStatus.GetCode() > 399 {
-			msg, _ := rResp.RawDataFull()
-			// Returning a `codeError` here will cause Resiliency to retry the request (if retries are enabled), but if the request continues to fail, the response is sent to the user with whatever status code the app returned.
-			return rResp, resiliency.NewCodeError(resStatus.GetCode(), codeError{
-				headers:     rResp.Headers(),
-				statusCode:  int(resStatus.GetCode()),
-				msg:         msg,
-				contentType: rResp.ContentType(),
-			})
+			if !req.IsStreamingRequest() {
```
Comment (acroca) [inline pkg/api/http/directmessaging.go]: Can't we do early return if it's a streaming request?

File: pkg/messaging/direct_messaging.go [hunk 2]
```diff
@@ -212,7 +212,16 @@ func (d *directMessaging) invokeWithRetry(
 	req *invokev1.InvokeMethodRequest,
 ) (*invokev1.InvokeMethodResponse, error) {
 	if !d.resiliency.PolicyDefined(app.id, resiliency.EndpointPolicy{}) {
-		// This policy has built-in retries so enable replay in the request
+		// Streaming requests cannot be retried since the body has already
+		// been consumed, so invoke once and return immediately.
+		if req.IsStreamingRequest() {
```
Comment (acroca) [inline pkg/messaging/direct_messaging.go]: Can we make this check as part of the previous `if`? The code here is doing the same as what's after that `if`, except for the warning

File: pkg/api/http/directmessaging.go (hunk 1 above)
Comment (JoshVanL) [reply pkg/api/http/directmessaging.go]: Thanks

File: pkg/messaging/direct_messaging.go (hunk 2 above)
Comment (JoshVanL) [reply pkg/messaging/direct_messaging.go]: Thanks

File: pkg/api/http/directmessaging.go
Comment (JoshVanL) [reply pkg/api/http/directmessaging.go]: :+1:

File: pkg/api/http/directmessaging.go (hunk 1 above)
Comment (acroca) [reply pkg/api/http/directmessaging.go]: That's not what I meant, I meant to do an early return if the response is streaming and not 2xx/3xx, return right away... Do we really need to go through the rest of that function?

Comment (JoshVanL) [reply pkg/api/http/directmessaging.go]: We still need to do headers, no?

File: docs/release_notes/v1.17.2.md [hunk 3]
```diff
@@ -6,6 +6,8 @@ This update includes a breaking change and bug fixes:
 - [Pub/sub messages incorrectly routed to dead-letter queue during graceful shutdown](#pubsub-messages-incorrectly-routed-to-dead-letter-queue-during-graceful-shutdown)
 - [Scheduler jobs with Drop failure policy may fire more than once during host reconnection](#scheduler-jobs-with-drop-failure-policy-may-fire-more-than-once-during-host-reconnection)
 - [Scheduler fails to start due to trailing dot in cluster domain DNS lookup](#scheduler-fails-to-start-due-to-trailing-dot-in-cluster-domain-dns-lookup)
+- [Service invocation buffers entire streaming request body in memory](#service-invocation-buffers-entire-streaming-request-body-in-memory)
+- [Service invocation buffers entire streaming response body in memory](#service-invocation-buffers-entire-streaming-response-body-in-memory)
```
Comment (cicoyle) [inline docs/release_notes/v1.17.2.md:10]:
```suggestion
```

is this dupped?

Comment (cicoyle) [reply docs/release_notes/v1.17.2.md:10]: I see 2 sections below, can they be combined or at least titled differently?

**Review by cicoyle — CHANGES_REQUESTED** [review]

File: docs/release_notes/v1.17.2.md (hunk 3 above)
Comment (olitomlinson) [reply docs/release_notes/v1.17.2.md:10]: One is request one is response 😀

Comment (cicoyle) [reply docs/release_notes/v1.17.2.md:10]: oh I see that now :)

**Review by cicoyle — APPROVED** [review]
