### PR TITLE
Fix calling programmatic subscriptions before app ready

### LINKED ISSUE #7938: Sidecar crashes on startup with existing Java test for service invocation
## In what area(s)?

/area runtime

> /area operator

> /area placement

> /area docs

> /area test-and-release

## What version of Dapr?

> 1.1.x
> 1.0.x
> edge: output of `git describe --dirty`
1.14.0-rc.5

## Expected Behavior

Service invocation with gRPC works with Java app and not crash.

## Actual Behavior

Run the MethodInvokeIT and see the test failing:

`Fatal error from runtime: failed to init programmatic subscriptions: rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing: dial tcp 127.0.0.1:54244: connect: connection refused`

As seen here:

```
== APP == Service to start on port 54244 ...
== APP == Artificial delay of 10 seconds ...
== APP == Now starting ...
== APP == Server: started listening on port 54244
time="2024-07-23T15:02:01.151672-03:00" level=info msg="application discovered on port 54244" app_id=methodinvokeitgrpc-methodinvokeservice instance=Arturs-Laptop.local scope=dapr.runtime type=log ver=1.14.0-rc.5
time="2024-07-23T15:02:01.151789-03:00" level=warning msg="Error processing operation DaprBuiltInInitializationRetries. Retrying in 509.117599ms…" app_id=methodinvokeitgrpc-methodinvokeservice instance=Arturs-Laptop.local scope=dapr.runtime type=log ver=1.14.0-rc.5
Checking if Dapr application has started ...
  APP ID                                  HTTP PORT  GRPC PORT  APP PORT  COMMAND               AGE  CREATED              DAPRD PID  CLI PID  APP PID  RUN TEMPLATE PATH  APP LOG PATH  DAPRD LOG PATH  RUNTEMPLATENAME  
  methodinvokeitgrpc-methodinvokeservice  54245      54246      54244     mvn exec:java -D ...  6s   2024-07-23 15:01.55  79901      79898    79902                                                                      
Checking if app is listening on port ...
Checking port 54244 ...
Confirmed listening on port 54244.
Checking if Dapr is listening on HTTP port ...
Checking port 54245 ...
Confirmed listening on port 54245.
Checking if Dapr is listening on GRPC port ...
Checking port 54246 ...
Confirmed listening on port 54246.
Dapr application started.
time="2024-07-23T15:02:03.042747-03:00" level=error msg="error getting topic list from app: rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing: dial tcp 127.0.0.1:54244: connect: connection refused\"" app_id=methodinvokeitgrpc-methodinvokeservice instance=Arturs-Laptop.local scope=dapr.runtime.processor.subscription type=log ver=1.14.0-rc.5
time="2024-07-23T15:02:03.043493-03:00" level=info msg="Dapr is shutting down" app_id=methodinvokeitgrpc-methodinvokeservice instance=Arturs-Laptop.local scope=dapr.runtime type=log ver=1.14.0-rc.5
time="2024-07-23T15:02:03.043595-03:00" level=info msg="Shutting down component statestore (state.redis/v1)" app_id=methodinvokeitgrpc-methodinvokeservice instance=Arturs-Laptop.local scope=dapr.runtime type=log ver=1.14.0-rc.5
time="2024-07-23T15:02:03.044199-03:00" level=info msg="Shutting down workflow engine" app_id=methodinvokeitgrpc-methodinvokeservice instance=Arturs-Laptop.local scope=dapr.runtime type=log ver=1.14.0-rc.5
time="2024-07-23T15:02:03.045177-03:00" level=info msg="stopping mDNS server for app id: methodinvokeitgrpc-methodinvokeservice" app_id=methodinvokeitgrpc-methodinvokeservice component="nr (mdns/v1)" instance=Arturs-Laptop.local scope=dapr.contrib type=log ver=1.14.0-rc.5
time="2024-07-23T15:02:03.047435-03:00" level=info msg="Closing HTTP server [::]:54245…" app_id=methodinvokeitgrpc-methodinvokeservice instance=Arturs-Laptop.local scope=dapr.runtime.http type=log ver=1.14.0-rc.5
time="2024-07-23T15:02:03.047501-03:00" level=info msg="Shutting down component localSecretStore (secretstores.local.file/v1)" app_id=methodinvokeitgrpc-methodinvokeservice instance=Arturs-Laptop.local scope=dapr.runtime type=log ver=1.14.0-rc.5
time="2024-07-23T15:02:03.048447-03:00" level=info msg="Shutting down component redisconfigstore (configuration.redis/v1)" app_id=methodinvokeitgrpc-methodinvokeservice instance=Arturs-Laptop.local scope=dapr.runtime type=log ver=1.14.0-rc.5
time="2024-07-23T15:02:03.048681-03:00" level=info msg="Shutting down component messagebus (pubsub.redis/v1)" app_id=methodinvokeitgrpc-methodinvokeservice instance=Arturs-Laptop.local scope=dapr.runtime type=log ver=1.14.0-rc.5
time="2024-07-23T15:02:03.048818-03:00" level=info msg="Dapr runtime stopped" app_id=methodinvokeitgrpc-methodinvokeservice instance=Arturs-Laptop.local scope=dapr.runtime type=log ver=1.14.0-rc.5
time="2024-07-23T15:02:03.058377-03:00" level=fatal msg="Fatal error from runtime: failed to init programmatic subscriptions: rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing: dial tcp 127.0.0.1:54244: connect: connection refused\"" app_id=methodinvokeitgrpc-methodinvokeservice instance=Arturs-Laptop.local scope=dapr.runtime type=log ver=1.14.0-rc.5
```

## Steps to Reproduce the Problem

Run Java SDK's MethodInvokeIT: https://github.com/dapr/java-sdk/actions/runs/10063303430/job/27817787624?pr=1078

## Release Note

RELEASE NOTE:

### PR DESCRIPTION
**Pull request by JoshVanL**
Fix daprd from calling programmatic subscriptions before app becomes ready.

Fixes #7938

### CODE REVIEW

File: pkg/runtime/runtime.go [hunk 1]
```diff
@@ -650,10 +650,6 @@ func (a *DaprRuntime) initRuntime(ctx context.Context) error {
 		return err
 	}
 
-	if err := a.processor.Subscriber().InitProgramaticSubscriptions(ctx); err != nil {
```
Comment (artursouza) [inline pkg/runtime/runtime.go:653]: Is this called somewhere else?

Comment (JoshVanL) [reply pkg/runtime/runtime.go:653]: Yes, here https://github.com/dapr/dapr/blob/7ea7016c0150e6a7b7bc7c30e34d56f0001c5e90/pkg/runtime/processor/subscriber/subscriber.go#L242

**Review by artursouza — APPROVED** [review]
