### PR TITLE
Fixed: direct messaging panics if name resolver is not initialized

### LINKED ISSUE #5533: panic: runtime error: invalid memory address or nil pointer dereference
macos   10.15.7
CLI version: 1.9.1
Runtime version: 1.9.3

dapr run --app-id dicom-service --app-port 3000 --app-protocol http --dapr-http-port 3001  --dapr-http-max-request-size 1024 --dapr-grpc-port 3002  node .

curl http://localhost:3001/v1.0/invoke/dicom-service/method/series
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x44caea9]

goroutine 162 [running]:
github.com/dapr/dapr/pkg/messaging.(*directMessaging).getRemoteApp(0xc00017a0c0, {0xc000ae4be0?, 0x8020102?})
	/Users/runner/work/dapr/dapr/pkg/messaging/direct_messaging.go:309 +0xc9
github.com/dapr/dapr/pkg/messaging.(*directMessaging).Invoke(0xc00017a0c0, {0x5cf1208, 0xc000f08600}, {0xc000ae4be0?, 0x203000?}, 0xc00064b620?)
	/Users/runner/work/dapr/dapr/pkg/messaging/direct_messaging.go:126 +0x56
github.com/dapr/dapr/pkg/http.(*api).onDirectMessage.func1({0x5cf1208, 0xc000f08600})
	/Users/runner/work/dapr/dapr/pkg/http/api.go:1390 +0xba
github.com/dapr/dapr/pkg/resiliency.(*NoOp).EndpointPolicy.func1(0x53dd0f8?)
	/Users/runner/work/dapr/dapr/pkg/resiliency/noop.go:36 +0x27
github.com/dapr/dapr/pkg/http.(*api).onDirectMessage(0xc0006da000, 0xc000f08600)
	/Users/runner/work/dapr/dapr/pkg/http/api.go:1389 +0x6d6
github.com/fasthttp/router.(*Router).Handler(0xc00039a460, 0xc000f08600)
	/Users/runner/go/pkg/mod/github.com/fasthttp/router@v1.4.12/router.go:427 +0x871
github.com/dapr/dapr/pkg/diagnostics.(*httpMetrics).FastHTTPMiddleware.func1(0xc000f08600)
	/Users/runner/work/dapr/dapr/pkg/diagnostics/http_monitoring.go:227 +0x13b
github.com/dapr/dapr/pkg/diagnostics.HTTPTraceMiddleware.func1(0xc000f08600)
	/Users/runner/work/dapr/dapr/pkg/diagnostics/http_tracing.go:56 +0x1ad
github.com/valyala/fasthttp.(*Server).serveConn(0xc0006d66c0, {0x5d04c10?, 0xc00064e300})
	/Users/runner/go/pkg/mod/github.com/valyala/fasthttp@v1.40.0/server.go:2311 +0x1268
github.com/valyala/fasthttp.(*workerPool).workerFunc(0xc00055cd20, 0xc0006faa20)
	/Users/runner/go/pkg/mod/github.com/valyala/fasthttp@v1.40.0/workerpool.go:224 +0xa9
github.com/valyala/fasthttp.(*workerPool).getCh.func1()
	/Users/runner/go/pkg/mod/github.com/valyala/fasthttp@v1.40.0/workerpool.go:196 +0x38
created by github.com/valyala/fasthttp.(*workerPool).getCh
	/Users/runner/go/pkg/mod/github.com/valyala/fasthttp@v1.40.0/workerpool.go:195 +0x1b0
❌  The daprd process exited with error code: exit status 2

### PR DESCRIPTION
**Pull request by ItalyPaleAle**
Fixes #5533

### CODE REVIEW

File: pkg/messaging/direct_messaging.go [hunk 1]
```diff
@@ -333,6 +334,10 @@ func (d *directMessaging) getRemoteApp(appID string) (remoteApp, error) {
 		return remoteApp{}, err
 	}
 
+	if d.resolver == nil {
```
Comment (yaron2) [inline pkg/messaging/direct_messaging.go:337]: Can you add a unit test for this?

**Review by yaron2 — CHANGES_REQUESTED** [review]

File: pkg/messaging/direct_messaging.go (hunk 1 above)
Comment (ItalyPaleAle) [reply pkg/messaging/direct_messaging.go:341]: Done (there was no test at all for the method, so had to write one)

Comment (skyao) [reply pkg/messaging/direct_messaging.go:341]: Do we know when this d.resolver will be nil? And can this probleam be fixed or d.resolver will allways be nil after this problem happens? (it means that all service invoke will fail) If so, we need to add more clear log content to notify the user what happened here.

Comment (ItalyPaleAle) [reply pkg/messaging/direct_messaging.go:341]: See #5533 . It can be `nil` if it fails to be initialized - Dapr still inits, but we do show error messages at that time.

Comment (skyao) [reply pkg/messaging/direct_messaging.go:341]: OK. So if dapr succeed to init name resolver, this problem will be resolved and not be nil.

**Review by skyao — APPROVED** [review]
LGTM

**Review by yaron2 — APPROVED** [review]
