### PR TITLE
Ability to disable metrics exporter for helm-installed components and daprd

### LINKED ISSUE #2677: Daprd failed to start metric server due to address already in use even though configuration metric disabled.
## In what area(s)?
I ran into this issue while install ingress controller. my k8s cluster is on bare-metal 

I also disabled global configuration daprsystem.

Spec:
  Metric:
    Enabled:  false

this is  ingress-annotations.yaml  value file.
-----------------------------------------------------------------
controller:
  hostNetwork: true
  dnsPolicy: ClusterFirstWithHostNet
  podAnnotations:
    dapr.io/enabled: "true"
    dapr.io/app-id: "nginx-ingress"
    dapr.io/app-protocol: "http"
    dapr.io/app-port: "80"
    dapr.io/api-token-secret: "dapr-api-token"
    dapr.io/config: "ingress-config"
    dapr.io/log-as-json: "true"

ingress-config.yaml --- define Configuration (I already disable metric)
----------------------------------------------------------------------------------
---
apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: ingress-config
spec:
  tracing:
    samplingRate: "1"
  metric:
    enabled: false
  secrets:
    scopes:
      - storeName: kubernetes
        defaultAccess: deny
        allowedSecrets: ["dapr-api-token"]
---
apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: tracing
spec:
  tracing:
    samplingRate: "1"
  metric:
    enabled: false

After helm chart install 

helm install nginx ingress-nginx/ingress-nginx \
     --set controller.replicaCount=3 \
     -f config/ingress-annotations.yaml \
     --set "controller.service.type=NodePort" \
         --set controller.service.externalIPs[0]="[pub id]" \
     -n default

helm deploy success but nginx-ingress-nginx pods CrashLoopBackOff due to daprd failed to start metrics server: listen tcp :9090: bind: address already in use

 kubectl get pods | grep nginx
nginx-ingress-nginx-controller-7b5fdb7976-c8tc6       1/2     CrashLoopBackOff   1          17s
nginx-ingress-nginx-controller-7b5fdb7976-rzhq8       0/2     CrashLoopBackOff   1          17s
nginx-ingress-nginx-controller-7b5fdb7976-v6hrx       1/2     CrashLoopBackOff   1          17s

Here are daprd container logs:
 
kubectl logs nginx-ingress-nginx-controller-7b5fdb7976-c8tc6 -c daprd
{"app_id":"nginx-ingress","instance":"archdev-worker1","level":"info","msg":"starting Dapr Runtime -- version 0.11.3 -- commit a1a8e11","scope":"dapr.runtime","time":"2021-01-18T00:44:25.680150038Z","type":"log","ver":"0.11.3"}
{"app_id":"nginx-ingress","instance":"archdev-worker1","level":"info","msg":"log level set to: info","scope":"dapr.runtime","time":"2021-01-18T00:44:25.680193038Z","type":"log","ver":"0.11.3"}
{"app_id":"nginx-ingress","instance":"archdev-worker1","level":"info","msg":"metrics server started on :9090/","scope":"dapr.metrics","time":"2021-01-18T00:44:25.68033324Z","type":"log","ver":"0.11.3"}
{"app_id":"nginx-ingress","instance":"archdev-worker1","level":"fatal","msg":"failed to start metrics server: listen tcp :9090: bind: address already in use","scope":"dapr.metrics","time":"2021-01-18T00:44:25.680742647Z","type":"log","ver":"0.11.3"}

> /area runtime
> /area operator
> /area placement
> /area docs
> /area test-and-release

## What version of Dapr?
1.0.0-rc.1

## Expected Behavior

since metric is disabled  daprd should installed successfully.

## Actual Behavior

 daprd  failed due to metric server address in use 

## Steps to Reproduce the Problem
export INGRESS_NAMESPACE="default"
kubectl apply -f config/namespace.yml -n $INGRESS_NAMESPACE
export API_TOKEN=$(openssl rand -base64 32)
kubectl create secret generic dapr-api-token --from-literal=token="${API_TOKEN}" -n $INGRESS_NAMESPACE

kubectl apply -f config/ingress-config.yaml -n $INGRESS_NAMESPACE
helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
helm repo update
helm install nginx ingress-nginx/ingress-nginx \
     --set controller.replicaCount=3 \
     -f config/ingress-annotations.yaml \
     --set "controller.service.type=NodePort" \
     --set controller.service.externalIPs[0]="our public ip" \
     -n  $INGRESS_NAMESPACE

------------------------------------------
here is namespace.yaml

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secret-reader
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: dapr-secret-reader
subjects:
- kind: ServiceAccount
  name: default
roleRef:
  kind: Role
  name: secret-reader
  apiGroup: rbac.authorization.k8s.io

### PR DESCRIPTION
**Pull request by pkedy**
# Description

This PR makes the following minor tweaks with regards to the `--enable-metrics` flag.

* Pass `--enable-metrics=false` in helm where appropriate when `global.prometheus.enabled=false`. This will disable the prometheus exporter (listening port) for the dapr system components (does not include `daprd`).
* For `daprd`, add `dapr.io/enable-metrics` annotation to the sidecar injector so it can pass `true` or `false` to the `--enable-metrics` flag of `daprd`
* Add the `--enable-metrics` flag to `daprd` which was absent before this PR
* Add `EnableMetrics` to `AppDescription` in `/test/platforms/kubernetes/app_description.go` in case that is a needed setting for tests in the future

## Issue reference

Resolves #2677 - @pzou19741 should be able to prevent `daprd` from listening on port 9090 by adding the `dapr.io/enable-metrics: "true"` annotation to his deployment. 

If this PR is merged, I will look through the docs site for any pages that need to be updated with this information. This most likely page is [here](https://docs.dapr.io/operations/monitoring/metrics/metrics-overview/). Setting `enabled: false` in the `metric` spec configuration may only disable metric collection but still initialize the exporter to listen on `--metrics-port`.

## Checklist

* [x] Code compiles correctly
* [x] Created/updated tests
* [x] Unit tests passing
* [ ] End-to-end tests passing
* [ ] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Specification has been updated / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Provided sample for the feature / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

### CODE REVIEW

File: tests/platforms/kubernetes/app_description.go [hunk 1]
```diff
@@ -16,6 +16,7 @@ type AppDescription struct {
 	RegistryName      string
 	Replicas          int32
 	IngressEnabled    bool
+	EnableMetrics     string
```
Comment (artursouza) [inline tests/platforms/kubernetes/app_description.go:19]: nit: `MetricsEnabled` to follow the pattern from similar properties above.

Comment (pkedy) [reply tests/platforms/kubernetes/app_description.go:19]: @artursouza I actually had it called that however the setting is `--enabled-metrics` throughout the Dapr components so I stuck with `EnabledMetrics` for consistency.

**Review by artursouza — COMMENTED** [review]
Just a nit. LGTM

File: tests/platforms/kubernetes/app_description.go (hunk 1 above)
Comment (artursouza) [reply tests/platforms/kubernetes/app_description.go:19]: I understand that but you can see how this struct follows a different pattern.

**Comment by artursouza** [comment]
Please, review E2E tests.

File: tests/platforms/kubernetes/app_description.go (hunk 1 above)
Comment (pkedy) [reply tests/platforms/kubernetes/app_description.go]: I changed it back and also made it a `bool` to be consistent with the other settings. That means having to set it to `true` because that is was the behavior before. It's likely the e2e tests don't require metrics I but played it safe and set it to `true` everywhere.

**Review by artursouza — APPROVED** [review]
