### PR TITLE
Fix ServiceInvocation response stream buffering

### LINKED ISSUE #9626: [Service Invoke] HTTP Responses which are streamed via chunked transfer are buffered in sidecar
Probably affects all versions of dapr

---

Full repro instructions here 

https://github.com/olitomlinson/dapr-large-file-streaming/blob/ui/STREAMING_RESPONSE_ISSUE.md

**MAKE SURE TO SWAP TO THE `UI` BRANCH AS `MAIN` IS A DIFFERENT ISSUE**

---

**Actual**

When a request is made which returns a streamed response, the **entire response** is buffered in the sidecar memory.

**Expected**

When a request is made which returns a streamed response, the entire response is NOT buffered in the sidecar memory.

### PR DESCRIPTION
**Pull request by JoshVanL**
The HTTP channel's response recorder (RWRecorder) buffered the entire response body in a bytes.Buffer before returning headers to the caller. For large streaming responses, this caused the receiver sidecar's memory to spike proportionally to the response size (e.g. ~750MB for a 256MB response).

Replace RWRecorder with a streaming rwRecorder backed by io.Pipe. The middleware pipeline now runs in a goroutine, writing response data to the pipe. The main goroutine waits for headers via a channel, then returns the pipe reader as the response body — data flows through without buffering.

Also flush chunked response data on the sender sidecar by wrapping the HTTP response writer with a flushWriter that calls Flush() after each Write, ensuring data reaches the client immediately instead of sitting in Go's 4KB bufio.Writer buffer.

Needs backporting but no release notes as this fix is related to the release notes already added.

Fixes https://github.com/dapr/dapr/issues/9626

### CODE REVIEW

File: pkg/api/http/directmessaging.go [hunk 1]
```diff
@@ -256,7 +256,15 @@ func (a *api) onDirectMessage(w http.ResponseWriter, r *http.Request) {
...
 		if !isSSE {
 			w.WriteHeader(statusCode)
-			_, rErr = io.Copy(w, reader)
+			// Use a flushing writer to ensure each chunk is sent to the
+			// client immediately. Without this, Go's HTTP server buffers
+			// the response in a 4KB bufio.Writer, preventing true
+			// streaming for chunked responses.
+			dst := io.Writer(w)
+			if f, ok := w.(http.Flusher); ok {
+				dst = &flushWriter{w: w, f: f}
```
Comment (acroca) [inline pkg/api/http/directmessaging.go:265]: Can't we just do `defer f.Flush()`? or move this `if` after the copy and flush directly. Won't that be easier?

File: pkg/channel/http/http_channel.go [hunk 2]
```diff
@@ -245,53 +245,83 @@ func (h *Channel) sendJob(ctx context.Context, name string, data *anypb.Any) (*i
...
+		readyCh: make(chan struct{}),
+	}
 
-	execPipeline.ServeHTTP(rw, channelReq)
-	resp := rw.Result() //nolint:bodyclose
+	var handlerErr error
+
+	go func() {
+		defer pw.Close()
+		defer rw.signalReady()
```
Comment (acroca) [inline pkg/channel/http/http_channel.go]: Don't we want to close first?

```suggestion
		defer rw.signalReady()
		defer pw.Close()
```

File: pkg/channel/http/rwrecorder.go [hunk 3]
```diff
@@ -1,111 +1,50 @@
...
 )
 
-type RWRecorder struct {
+// rwRecorder writes response body data to an io.PipeWriter and signals when
+// headers and status code are available.
+type rwRecorder struct {
 	statusCode int
 	h          http.Header
-	W          io.ReadWriter
+	pw         *io.PipeWriter
```
Comment (acroca) [inline pkg/channel/http/rwrecorder.go]: We could use `io.Writer` instead to make it less implementation specific no?

File: pkg/api/http/directmessaging.go (hunk 1 above)
Comment (JoshVanL) [reply pkg/api/http/directmessaging.go:265]: No because this means we would only flush once, rather than on every `Write` which matters for chunked calls. Means we would continue to buffer the whole thing in memory which we are trying to avoid.

File: pkg/channel/http/http_channel.go (hunk 2 above)
Comment (JoshVanL) [reply pkg/channel/http/http_channel.go]: Addressed

File: pkg/channel/http/rwrecorder.go (hunk 3 above)
Comment (JoshVanL) [reply pkg/channel/http/rwrecorder.go]: Addressed

**Review by acroca — APPROVED** [review]
