### PR TITLE
Removing reuse of backoff.NewExponentialBackOff()

### LINKED ISSUE #2705: Actor reminders persist beyond unregister intermittently
## In what area(s)?

/area runtime
> /area operator
> /area placement
> /area docs
> /area test-and-release

## What version of Dapr?

CLI version: 1.0.0-rc.3
Runtime version: 1.0.0-rc.1

## Expected Behavior

Unregistered reminders should not start firing again when dapr is stopped and restarted. 

## Actual Behavior

They do start firing again. It's intermittent, so with a single actor + reminder it might work correctly. But if you start up 10 at a time the chances are pretty good that this behavior will occur. I have replicated it both locally and in AKS.

## Steps to Reproduce the Problem

* Activate an actor
* register a reminder
* let it fire a couple of times
* unregister the reminder
* stop the app (ctrl-c or delete the pod) 
* Restart it with the same command line as before (dapr run or deployment recreates pod)

I slightly modified the actor sample from the dotnet-sdk repo to show the problem. Here is a repo with the changed app plus logs from running it with both redis and cosmosdb as the actor state store.

https://github.com/sebastus/dapr-actor-reminders

## Release Note

RELEASE NOTE:

### PR DESCRIPTION
**Pull request by pkedy**
[backoff.NewExponentialBackOff() is not thread safe](https://github.com/cenkalti/backoff/blob/v4/exponential.go#L52-L67) and should not be reused so this PR moves it to each `backoff.Retry` call.

This is a small fix to #2848
Resolves #2705

Edit: I also noticed that `actors_test.go` was flaky and failing frequently (It did for me in this PR). Upon investigation I found that there was a race condition due to relying on `time.Sleep` and checking an invocation count at an exact moment where the first invocation had occurred. This works most of the time but it is likely that the Go scheduler/build orchestrator might to be preventing 100% reliability.

The real intent of the test is to verify that a reminder is scheduled to trigger before any previously scheduled reminders triggers before the others. Instead of sleeping for an exact duration, I changed the test to leverage a channel and inspect the first request written to it. My hope is that this will resolve the periodic failure in this test. It also shaves a little bit of time of the test ;)

## Checklist

* [x] Code compiles correctly
* [x] Created/updated tests
* [x] Unit tests passing
* [ ] End-to-end tests passing
* [ ] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Specification has been updated / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Provided sample for the feature / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

### CODE REVIEW

File: pkg/actors/actors_test.go [hunk 1]
```diff
@@ -32,6 +31,31 @@ const (
 	TestKeyName = "key0"
 )
 
+// testRequest is the request object that encapsulates the `data` field of a request
+type testRequest struct {
+	Data interface{} `json:"data"`
+}
+
+type mockAppChannel struct {
```
Comment (artursouza) [inline pkg/actors/actors_test.go:39]: Why do we need this refactoring?

**Review by artursouza — CHANGES_REQUESTED** [review]

File: pkg/actors/actors_test.go (hunk 1 above)
Comment (pkedy) [reply pkg/actors/actors_test.go:39]: You beat me before I could add the additional information :-)
See the details above.

**Review by artursouza — APPROVED** [review]
