### PR TITLE
Fix subscriptionScopes configuration error causing panic

### LINKED ISSUE #4054: Error in component field causing daprd panic
**In what area(s)?**
/area runtime

**What version of Dapr?**
1.5.0
 
**Expected Behavior**
There won't be panic

**Actual Behavior**
generate panci

**the component yaml**
```# ------------------------------------------------------------
# Copyright (c) Microsoft Corporation and Dapr Contributors.
# Licensed under the MIT License.
# ------------------------------------------------------------

apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: redis-pubsub
  namespace: mesoid
spec:
  type: pubsub.redis
  version: v1
  metadata:
#   required
    - name: redisHost
      value: "dapr-redis-svc:45454"
    - name: redisPassword
      value: "1234"
    - name: consumerID
      value: "123" 
    - name: processingTimeout
      value: 3 
    - name: redeliverInterval
      value: 3
    - name: queueDepth
      value: 3
    - name: concurrency
      value: 3
    - name: maxLenApprox
      value: 3
    - name: subscriptionScopes
      value: "dp-61c2cb20562850d49d47d1c7-executorapp"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dapr-redis-config
  namespace: mesoid
data:
  redis.conf: |
    bind 0.0.0.0
    port 6379
    requirepass 1234
    appendonly yes
    protected-mode no
---
apiVersion: v1
kind: Pod
metadata:
  name: dapr-redis
  namespace: mesoid
  labels:
    app: dapr-redis-test
spec:
  containers:
    - name: redis
      image: redis:latest
      command:
        - sh
        - -c
        - exec redis-server /usr/local/etc/redis/redis.conf
      ports:
        - containerPort: 6379
      volumeMounts:
        - name: redis-config
          mountPath: /usr/local/etc/redis
  volumes:
    - name: redis-config
      configMap:
        name: dapr-redis-config
---
kind: Service
apiVersion: v1
metadata:
  name: dapr-redis-svc
  namespace: mesoid
  labels:
    app: dapr-redis-test
spec:
  type: NodePort
  selector:
    app: dapr-redis-test
  ports:
    - protocol: TCP
      port: 45454
      targetPort: 6379

```
**Steps to Reproduce the Problem**
daprd is already in operation
 kubectl apply -f test.yaml  
 then wait many sennds
image

### PR DESCRIPTION
**Pull request by CrazyHZM**
Signed-off-by: crazyhzm <crazyhzm@gmail.com>

# Description

## Issue reference
Fix #4054

## Checklist

Please make sure you've  completed the relevant tasks for this PR, out of the following list:

* [x] Code compiles correctly
* [x] Created/updated tests
* [x] Unit tests passing
* [x] End-to-end tests passing
* [x] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [x] Specification has been updated / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [x] Provided sample for the feature / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

### CODE REVIEW

File: pkg/scopes/scopes.go [hunk 1]
```diff
@@ -26,7 +26,7 @@ func GetScopedTopics(scope, appID string, metadata map[string]string) []string {
 		apps := strings.Split(val, appsSeparator)
 		for _, a := range apps {
 			appTopics := strings.Split(a, appSeparator)
-			if len(appTopics) == 0 {
+			if len(appTopics) < 2 {
```
Comment (daixiang0) [inline pkg/scopes/scopes.go:29]: Please add false cases.

Comment (CrazyHZM) [reply pkg/scopes/scopes.go:29]: Has been added in the unit test

**Review by tanvigour — APPROVED** [review]
