### PR TITLE
Fix: Bulk pubsub subscriber panics when tracing is disabled

### LINKED ISSUE #6099: Bulk pubsub subscriber panics when tracing is disabled
## In what area(s)?

/area runtime

## What version of Dapr?

> 1.10.x
> master

## Description

Using bulk pubsub to subscribe to a topic, Daprd panics if tracing is disabled.

The bug is in these lines (and in another similar spot in the same file):

https://github.com/dapr/dapr/blob/585da2feb90d5ddbc5a94efca5ba0702a9e43808/pkg/runtime/bulk_subscriber.go#L587-L588

When tracing is disabled, `diag.StartInternalCallbackSpan` returns `nil` for `span`, so the next line panics.

## Release Note

RELEASE NOTE: **FIX** Bulk pubsub subscriber panics when tracing is disabled

### PR DESCRIPTION
**Pull request by ItalyPaleAle**
Fixes #6099 by backporting changes from #6101

### CODE REVIEW

File: pkg/runtime/bulk_subscriber.go [hunk 1]
```diff
@@ -561,8 +561,12 @@ func (a *DaprRuntime) publishBulkMessageGRPC(ctx context.Context, bulkSubCallDat
 		items[i] = item
 	}
 
+	uuidObj, err := uuid.NewRandom()
+	if err != nil {
+		return fmt.Errorf("failed to generate UUID: %w", err)
+	}
 	envelope := &runtimev1pb.TopicEventBulkRequest{
-		Id:         uuid.New().String(),
+		Id:         uuidObj.String(),
```
Comment (ItalyPaleAle) [inline pkg/runtime/bulk_subscriber.go:569]: This is not related to tracing but was fixed in #6101 too. In short, `uuid.New()` can panic (if there's not enough entropy in the kernel), while `uuid.NewRandom()` allows retrieving an error.

**Review by yaron2 — APPROVED** [review]
