### PR TITLE
Log error about app-port to be set if a pub/sub component is loaded without app-port

### LINKED ISSUE #2979: Dapr should require app-port to be set if a pub/sub component is loaded/used
## In what area(s)?
Use of pub/sub components should be prevented if no app-port is set on dapr when it is started, which is needed for dapr to successfully call the subscription endpoints.

When debugging an issue on pub/sub the subscriber service for the topics did not have an **app-port set, so dapr was receiving the topic events successfully from the publisher but could not send these to the listening app. It was hard to find this issue since the components loaded successfully and there were no errors in the logs. There needs to be check and a error message written to find this condition and even fail dapr from successfully starting.
 
> /area runtime
> /area pubsub

## What version of Dapr?
1.0.1

## Expected Behavior

There needs to be check and a error message written to find this condition and even fail dapr from successfully starting.

## Actual Behavior

No error and no failure on this condition.

## Steps to Reproduce the Problem

Run the pub/sub sample and remove the --app-port CLI setting from the subscriber. Everything starts ok, but the sample does not work.

## Release Note

**UPDATE**

We cannot enforce app port for pubsub since publishers do not need to provide one, on the other hand, we can log warning when pubsub is loaded but app is not listening to a port.

RELEASE NOTE: Log missing app port when pub/sub component is loaded.

### PR DESCRIPTION
**Pull request by beiwei30**
# Description

fix #2979

## Issue reference

We strive to have all PR being opened based on an issue, where the problem or feature have been discussed prior to implementation.

Please reference the issue this PR will close: #2979

## Checklist

Please make sure you've  completed the relevant tasks for this PR, out of the following list:

* [x] Code compiles correctly
* [x] Created/updated tests
* [x] Unit tests passing
* [x] End-to-end tests passing
* [ ] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Specification has been updated / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Provided sample for the feature / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

### CODE REVIEW

**Review by halspang — COMMENTED** [review]
It seems like this violates what both Ryan and Yaron were stating in the issue. We wanted to add additional logging not make the request fail. @yaron2, thoughts?

File: pkg/runtime/runtime.go [hunk 1]
```diff
@@ -968,13 +968,14 @@ func (a *DaprRuntime) getTopicRoutes() (map[string]TopicRoute, error) {
 		return a.topicRoutes, nil
 	}
 
-	var topicRoutes map[string]TopicRoute = make(map[string]TopicRoute)
-
 	if a.appChannel == nil {
-		return topicRoutes, nil
+		return nil, errors.New("app channel not initialized, make sure -app-port is specified")
```
Comment (artursouza) [inline pkg/runtime/runtime.go:972]: See the original issue. There is a comment about this: https://github.com/dapr/dapr/issues/2979#issuecomment-807906198

A publisher does not need to expose a port, so this would artificially create a requirement.

**Review by artursouza — CHANGES_REQUESTED** [review]

File: pkg/runtime/runtime.go (hunk 1 above)
Comment (beiwei30) [reply pkg/runtime/runtime.go:972]: so if I don't misunderstand. We should log more instead of throw an error? If this is the case, I believe my change satisfy Yaron's comment, because

```go
func (a *DaprRuntime) startSubscribing() {
	for name, pubsub := range a.pubSubs {
		if err := a.beginPubSub(name, pubsub); err != nil {
			log.Errorf("error occurred while beginning pubsub %s: %s", name, err)
		}
	}
}
```

Comment (beiwei30) [reply pkg/runtime/runtime.go:972]: @artursouza @halspang would you mind to shine more light on this?

**Comment by beiwei30** [comment]
> It seems like this violates what both Ryan and Yaron were stating in the issue. We wanted to add additional logging not make the request fail. @yaron2, thoughts?

@halspang, pls. check https://github.com/dapr/dapr/pull/3243#discussion_r646430841

File: pkg/runtime/runtime.go (hunk 1 above)
Comment (yaron2) [reply pkg/runtime/runtime.go:972]: @artursouza in this case the subscription part will error out, this will not affect publishing. @beiwei30 is correct.

**Review by artursouza — APPROVED** [review]

File: pkg/runtime/runtime.go (hunk 1 above)
Comment (artursouza) [reply pkg/runtime/runtime.go:972]: I am actually concerned about logging this as an error. It is only an error if app intended to have a subscription but does not have app-port - we would need to "guess" the app's intent.

**Review by artursouza — CHANGES_REQUESTED** [review]
Logging error for not having app-port is a bad experience when the app is a publisher only.

File: pkg/runtime/runtime.go (hunk 1 above)
Comment (yaron2) [reply pkg/runtime/runtime.go:972]: Right. maybe change to warning? @beiwei30

Comment (artursouza) [reply pkg/runtime/runtime.go:989]: Any updates?

Comment (beiwei30) [reply pkg/runtime/runtime.go:989]: noticed comments updated just now, will update the PR today.

Comment (beiwei30) [reply pkg/runtime/runtime.go]: @yaron2 @artursouza 

I've updated the change like this:

```go
if a.appChannel == nil {
		log.Warn("app channel not initialized, make sure -app-port is specified if pubsub subscription is required")
		return topicRoutes, nil
	}
```

Pls. note there's no way to judge there are subscriptions expected on application side when the app port is not present.

**Review by artursouza — DISMISSED** [review]

**Review by artursouza — APPROVED** [review]
