### PR TITLE
fix(pubsub): apply namespace prefix to topic in BulkPublish

### LINKED ISSUE #3663: Namespaced consumer groups doesn't work with Bulk pubsub on RabbitMQ
## Expected Behavior

Namespaced consumer groups should work as documented here: https://docs.dapr.io/developing-applications/building-blocks/pubsub/howto-namespace/#with-namespace-consumer-groups

## Actual Behavior
 
When adding the namespace configuration to rabbitmq component this fails to add the correct namespaced consumer group to the broker but instead does not take the namespace into account on topic or consumer group creation.

```
  - name: consumerID
    value: "{namespace}"
```

This works on regular pubsub, eg namespace= default and topic=orders
Image

On bulk pubsub, the publisher is just using orders topic.

Image

This was also tested and works fine on Redis so I believe is just a bug on RabbitMQ.

Image

## Steps to Reproduce the Problem

Run the repro sample here: https://github.com/alicejgibbons/dapr-bulk-pubsub-rabbit

## Release Note

RELEASE NOTE: **FIX** Bug in Dapr bulk pubsub with rabbitmq

### PR DESCRIPTION
**Pull request by lokeshkaki**
# Description

When `NamespaceScoped` is true, `Publish` prepends `p.namespace` to `req.Topic` before forwarding to the component. `BulkPublish` lacked this equivalent step, causing bulk-published messages to be routed to the un-namespaced exchange while subscribers listened on the namespaced topic, resulting in silent message loss.

This fix adds the namespace guard to `BulkPublish` in `publisher.go` immediately after scope validation, before either the native `BulkPublisher` or `defaultBulkPublisher` fallback path is invoked. A new test `TestNamespacedBulkPublisher` is added to `publisher_test.go` asserting that `req.Topic` is correctly prefixed when `NamespaceScoped` is true.

## Issue reference

Please reference the issue this PR will close: dapr/components-contrib#3663

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

- [x] Code compiles correctly
- [x] Created/updated tests
- [x] Unit tests passing
- [ ] End-to-end tests passing
- [ ] Extended the documentation / Created issue in the <https://github.com/dapr/docs/> repo: dapr/docs#_[issue number]_
- [ ] Specification has been updated / Created issue in the <https://github.com/dapr/docs/> repo: dapr/docs#_[issue number]_
- [ ] Provided sample for the feature / Created issue in the <https://github.com/dapr/docs/> repo: dapr/docs#_[issue number]_

### CODE REVIEW

**Comment by JoshVanL** [comment]
Thanks @lokeshkaki !
Please can we have a new integration test for this change? https://github.com/dapr/dapr/tree/master/tests/integration/suite/daprd/pubsub

**Comment by lokeshkaki** [comment]
> Thanks @lokeshkaki ! Please can we have a new integration test for this change? https://github.com/dapr/dapr/tree/master/tests/integration/suite/daprd/pubsub

@JoshVanL Thanks for the review! I added a new integration test at bulkpublishing.go to cover namespace-scoped BulkPublish behavior. I also validated it with focused and pubsub integration runs, both passing.

File: tests/integration/suite/daprd/pubsub/scopes/bulkpublishing.go [hunk 1]
```diff
@@ -0,0 +1,107 @@
...
+	"github.com/dapr/dapr/tests/integration/framework/process/daprd"
+	"github.com/dapr/dapr/tests/integration/framework/process/grpc/subscriber"
+	"github.com/dapr/dapr/tests/integration/suite"
+)
+
+func init() {
+	suite.Register(new(bulkpublishnamespace))
+}
+
+type bulkpublishnamespace struct {
```
Comment (acroca) [inline tests/integration/suite/daprd/pubsub/scopes/bulkpublishing.go]: The struct name should match the filename

**Review by acroca — COMMENTED** [review]
LGTM, just one small change

File: tests/integration/suite/daprd/pubsub/scopes/bulkpublishing.go (hunk 1 above)
Comment (lokeshkaki) [reply tests/integration/suite/daprd/pubsub/scopes/bulkpublishing.go]: done

**Review by acroca — APPROVED** [review]

**Review by JoshVanL — APPROVED** [review]

**Comment by marcduiker** [comment]
@holopin-bot @lokeshkaki runtime-badge Thank you! Here's a digital badge as a small token of appreciation.
